/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package is_team;

import javax.swing.JSlider;


/**
 *
 * @author tung
 */
public class Controller extends javax.swing.JFrame {

    /**
     * Creates new form Controller
     */
    public Controller() {
        initComponents();
        setTitle("Controller");
        createControllerTempSlider();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controllerPanel = new javax.swing.JPanel();
        controllerStateLabel = new javax.swing.JLabel();
        controllerStateCheckbox = new javax.swing.JCheckBox();
        controllerSpeedLabel = new javax.swing.JLabel();
        controllerSpeedSlider = new javax.swing.JSlider();
        controllerWindLabel = new javax.swing.JLabel();
        controllerWindSlider = new javax.swing.JSlider();
        controllerWindLeftLabel = new javax.swing.JLabel();
        controllerWindMiddleLabel = new javax.swing.JLabel();
        controllerWindRightLabel = new javax.swing.JLabel();
        controllerTempLabel = new javax.swing.JLabel();
        controllerTempSlider = new javax.swing.JSlider();
        controllerSpeedLeftLabel = new javax.swing.JLabel();
        controllerSpeedMiddleLabel = new javax.swing.JLabel();
        controllerSpeedRightLabel = new javax.swing.JLabel();
        controllerTempLeftLabel = new javax.swing.JLabel();
        controllerTempMiddleLabel = new javax.swing.JLabel();
        controllerTempRightLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controllerStateLabel.setText("State:");

        controllerStateCheckbox.setText("ON");

        controllerSpeedLabel.setText("Speed:");

        controllerSpeedSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                controllerSpeedSliderStateChanged(evt);
            }
        });

        controllerWindLabel.setText("Wind direction: ");

        controllerWindLeftLabel.setText("Left");

        controllerWindMiddleLabel.setText("Middle");

        controllerWindRightLabel.setText("Right");

        controllerTempLabel.setText("Temperature:");

        controllerTempSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                controllerTempSliderStateChanged(evt);
            }
        });

        controllerSpeedLeftLabel.setText("0km/h");

        controllerSpeedMiddleLabel.setText("50km/h");

        controllerSpeedRightLabel.setText("100km/h");

        controllerTempLeftLabel.setText("0℃");

        controllerTempMiddleLabel.setText("25℃");

        controllerTempRightLabel.setText("50℃");

        javax.swing.GroupLayout controllerPanelLayout = new javax.swing.GroupLayout(controllerPanel);
        controllerPanel.setLayout(controllerPanelLayout);
        controllerPanelLayout.setHorizontalGroup(
            controllerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controllerPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(controllerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(controllerTempLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(controllerSpeedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(controllerPanelLayout.createSequentialGroup()
                        .addGroup(controllerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(controllerWindLabel)
                            .addGroup(controllerPanelLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(controllerStateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(controllerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controllerPanelLayout.createSequentialGroup()
                        .addComponent(controllerWindLeftLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(controllerWindMiddleLabel)
                        .addGap(144, 144, 144)
                        .addComponent(controllerWindRightLabel))
                    .addComponent(controllerWindSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controllerPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(controllerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(controllerPanelLayout.createSequentialGroup()
                                .addComponent(controllerTempLeftLabel)
                                .addGap(164, 164, 164)
                                .addComponent(controllerTempMiddleLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(controllerTempRightLabel))
                            .addComponent(controllerStateCheckbox)
                            .addComponent(controllerSpeedSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(controllerTempSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(controllerPanelLayout.createSequentialGroup()
                                .addComponent(controllerSpeedLeftLabel)
                                .addGap(132, 132, 132)
                                .addComponent(controllerSpeedMiddleLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                                .addComponent(controllerSpeedRightLabel)))))
                .addContainerGap())
        );
        controllerPanelLayout.setVerticalGroup(
            controllerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controllerPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(controllerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(controllerStateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(controllerStateCheckbox))
                .addGap(18, 18, 18)
                .addGroup(controllerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(controllerTempLeftLabel)
                    .addComponent(controllerTempMiddleLabel)
                    .addComponent(controllerTempRightLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(controllerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(controllerTempSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(controllerTempLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(controllerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(controllerSpeedLeftLabel)
                    .addComponent(controllerSpeedMiddleLabel)
                    .addComponent(controllerSpeedRightLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controllerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(controllerSpeedLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(controllerSpeedSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(controllerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(controllerPanelLayout.createSequentialGroup()
                        .addGroup(controllerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(controllerWindRightLabel)
                            .addGroup(controllerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(controllerWindLeftLabel)
                                .addComponent(controllerWindMiddleLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(controllerWindSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(controllerWindLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controllerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controllerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void createControllerTempSlider(){
        controllerTempSlider.setMinimum(0);
        controllerTempSlider.setMaximum(50);
    }
    
    private void controllerTempSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_controllerTempSliderStateChanged
        // TODO add your handling code here:
        int currentTemp = ((JSlider)evt.getSource()).getValue();
        controllerTempLabel.setText("Temperature(" +
                String.valueOf(currentTemp)+ "℃): ");
    }//GEN-LAST:event_controllerTempSliderStateChanged

    private void controllerSpeedSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_controllerSpeedSliderStateChanged
        // TODO add your handling code here:
        int currentSpeed = ((JSlider)evt.getSource()).getValue();
        controllerSpeedLabel.setText("Speed(" +
                String.valueOf(currentSpeed)+ "km/h): ");
    }//GEN-LAST:event_controllerSpeedSliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Controller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controllerPanel;
    private javax.swing.JLabel controllerSpeedLabel;
    private javax.swing.JLabel controllerSpeedLeftLabel;
    private javax.swing.JLabel controllerSpeedMiddleLabel;
    private javax.swing.JLabel controllerSpeedRightLabel;
    private javax.swing.JSlider controllerSpeedSlider;
    private javax.swing.JCheckBox controllerStateCheckbox;
    private javax.swing.JLabel controllerStateLabel;
    private javax.swing.JLabel controllerTempLabel;
    private javax.swing.JLabel controllerTempLeftLabel;
    private javax.swing.JLabel controllerTempMiddleLabel;
    private javax.swing.JLabel controllerTempRightLabel;
    private javax.swing.JSlider controllerTempSlider;
    private javax.swing.JLabel controllerWindLabel;
    private javax.swing.JLabel controllerWindLeftLabel;
    private javax.swing.JLabel controllerWindMiddleLabel;
    private javax.swing.JLabel controllerWindRightLabel;
    private javax.swing.JSlider controllerWindSlider;
    // End of variables declaration//GEN-END:variables
}
